apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji-addons-collection
  namespace: flux-giantswarm
spec:
  dependsOn:
  - name: catalogs
  force: false
  interval: 5m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: kamaji-addons-collection
    namespace: flux-giantswarm
  retryInterval: 1m
  targetNamespace: giantswarm
  timeout: 3m
