---
# DeploymentRuntimeConfig for Azure resources
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: upbound-provider-family-azure
  labels:
    provider-family: azure
    provider-family-member: azure-family
spec:
  deploymentTemplate:
    metadata:
      annotations:
        azure.workload.identity/use: "true"
    spec:
      selector: {}
      template:
        metadata:
          annotations:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: upbound-provider-family-azure
          containers:
            - name: package-runtime
              args:
                - --debug
---
# DeploymentRuntimeConfig for Azure resources
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: upbound-provider-azure
  labels:
    provider-family: azure
    provider-family-member: azure-provider
spec:
  deploymentTemplate:
    metadata:
      annotations:
        azure.workload.identity/use: "true"
    spec:
      selector: {}
      template:
        metadata:
          annotations:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: upbound-provider-azure
          containers:
            - name: package-runtime
              args:
                - --debug
