apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
  - ./namespace.yaml
  - ./helm-release.yaml
  - ./mcp-kubernetes-values.yaml

configMapGenerator:
  - name: mcp-kubernetes-values
    namespace: flux-giantswarm
    files:
      - ./values.yaml
