patches:
  - target:
      kind: Konfiguration
      name: collection-konfiguration
      namespace: giantswarm
    patch: '[{"op": "add", "path": "/spec/targets/defaults/variables/-", "value": {"name": "stage", "value": "testing"}}]'
  - target:
      kind: App
      name: app-operator
      namespace: giantswarm
    patch: '[{"op": "replace", "path": "/spec/version", "value": "6.6.6"}]'
  - target:
      kind: App
      name: sloth-rules
      namespace: giantswarm
    patch: '[{"op": "replace", "path": "/spec/version", "value": "1.1.1"}]'
resources:
  - ../../base
