resources:
  - app-admission-controller.yaml
  - app-exporter.yaml
  - app-operator.yaml
  - athena.yaml
  - cloudnative-pg.yaml
  - cluster-apps-operator.yaml
  - cluster-cleaner.yaml
  - happa.yaml
  - konfigure-operator.yaml
  - prometheus-rules.yaml
