resources:
  - app-admission-controller.yaml
  - app-exporter.yaml
  - app-operator.yaml
  - athena.yaml
  - cloudnative-pg.yaml
  - cluster-api-events.yaml
  - cluster-api.yaml
  - cluster-apps-operator.yaml
  - cluster-cleaner.yaml
  - encryption-provider-operator.yaml
  - grafana.yaml
  - happa.yaml
  - ingress-nginx.yaml
  - konfigure-operator.yaml
  - kube-downscaler.yaml
  - kyverno-policies-dx.yaml
  - kyverno-policies-observability.yaml
  - kyverno-policies-ux.yaml
  - observability-operator.yaml
  - observability-platform-api.yaml
  - organization-operator.yaml
  - prometheus-remotewrite.yaml
  - prometheus-rules.yaml
  - sloth-rules.yaml
  - sloth.yaml
