resources:
  - app-admission-controller.yaml
  - app-exporter.yaml
  - app-operator.yaml
  - athena.yaml
  - cloudnative-pg.yaml
  - cluster-api-events.yaml
  - cluster-api.yaml
  - cluster-apps-operator.yaml
  - cluster-cleaner.yaml
  - dashboards.yaml
  - encryption-provider-operator.yaml
  - grafana.yaml
  - happa.yaml
  - ingress-nginx.yaml
  - keda.yaml
  - konfigure-operator.yaml
  - kube-downscaler.yaml
  - kyverno-policies-connectivity.yaml
  - kyverno-policies-dx.yaml
  - kyverno-policies-observability.yaml
  - kyverno-policies-ux.yaml
  - loki.yaml
  - mimir.yaml
  - oauth2-proxy.yaml
  - observability-operator.yaml
  - observability-platform-api.yaml
  - organization-operator.yaml
  - plugin-barman-cloud.yaml
  - prometheus-remotewrite.yaml
  - prometheus-rules.yaml
  - rbac-operator.yaml
  - silence-operator.yaml
  - sloth-rules.yaml
  - sloth.yaml
  - starboard-exporter.yaml
