namePrefix: common-
resources:
  - jobscrapingfailure.yaml
  - atlas-managementclustercertificateismissing.yaml
  - atlas-mimirrulerruleevaluationfailures.yaml
  - mimiralertmanagernotificationsfailing.yaml
  - grafana-down.yaml
