namePrefix: common-
resources:
  - jobscrapingfailure.yaml
  - atlas-managementclustercertificateismissing.yaml
  - atlas-mimirrulerruleevaluationfailures.yaml
  - atlas-grafanapostgresqlrecoverytestfailed.yaml
  - mimiralertmanagernotificationsfailing.yaml
