apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: mimiralertmanagernotificationsfailing
  annotations:
    motivation: "Waiting for cluster upgrade"
    github_issue: https://github.com/giantswarm/roadmap/issues/4030
    valid-until: "2025-12-01"
  namespace: monitoring
spec:
  matchers:
    - name: alertname
      value: MimirAlertmanagerNotificationsFailing
      matchType: "="
    - name: cluster_id
      value: ".*"
      matchType: "=~"
