apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    apps-to-teams-mapping: "true"
  name: apps-to-teams-mapping
  namespace: giantswarm
data:
  alertmanager-to-github: atlas
  alloy: atlas
  app-admission-controller: honeybadger
  app-exporter: honeybadger
  app-operator: honeybadger
  athena: shield
  auth-bundle: shield
  aws-cloud-controller-manager-app: phoenix
  aws-ebs-csi-driver-bundle: phoenix
  aws-ebs-csi-driver: phoenix
  aws-ebs-csi-driver-servicemonitors: phoenix
  aws-efs-csi-driver-bundle: phoenix
  aws-efs-csi-driver: phoenix
  aws-lb-controller-bundle: phoenix
  aws-load-balancer-controller: phoenix
  aws-node-termination-handler: phoenix
  aws-nth-bundle: phoenix
  aws-nth-crossplane-resources: phoenix
  aws-pod-identity-webhook: phoenix
  aws-resolver-rules-operator: phoenix
  aws-vpc-operator: phoenix
  azure-ad-pod-identity-app: phoenix
  azure-cloud-controller-manager-app: phoenix
  azure-cloud-node-manager-app: phoenix
  azure-private-endpoint-operator: phoenix
  azure-workload-identity-webhook: phoenix
  azuredisk-csi-driver-app: phoenix
  azurefile-csi-driver-app: phoenix
  backstage: honeybadger
  caicloud-event-exporter-app: honeybadger
  capa-iam-operator: phoenix
  cert-exporter: tenet
  cert-manager-app: shield
  chart-operator: honeybadger
  cilium: cabbage
  cilium-crossplane-resources: phoenix
  cilium-servicemonitors: cabbage
  cloud-provider-cloud-director: rocket
  proxmox-cloud-controller-manager: rocket
  cloud-provider-vsphere: rocket
  cloudnative-pg: shield
  cluster: tenet
  cluster-api: tenet
  cluster-api-control-plane-provider-kamaji: rocket
  cluster-api-events: tenet
  cluster-api-ipam-provider-in-cluster: rocket
  cluster-api-monitoring: tenet
  cluster-api-provider-aws: phoenix
  cluster-api-provider-azure: phoenix
  cluster-api-provider-cloud-director: rocket
  cluster-api-provider-proxmox: rocket
  cluster-api-provider-vsphere: rocket
  cluster-apps-operator: honeybadger
  cluster-autoscaler-app: tenet
  cluster-aws: phoenix
  cluster-azure: phoenix
  cluster-cleaner: tenet
  cluster-cloud-director: rocket
  cluster-eks: phoenix
  cluster-vsphere: rocket
  coredns-app: cabbage
  coredns-extensions: cabbage
  crossplane: honeybadger
  csi-driver-nfs: rocket
  csi-external-snapshotter-app: rocket
  dashboards: atlas
  debug-toolbox: planeteers
  dex-app: shield
  dex-operator: shield
  dns-operator-azure: phoenix
  dns-operator-route53: rocket
  docs-indexer-app: honeybadger
  encryption-config-hasher: phoenix
  encryption-provider-operator: phoenix
  envoy-ai-gateway: cabbage
  envoy-gateway: cabbage
  etcd-backup-operator: tenet
  etcd-defrag: tenet
  etcd-kubernetes-resources-count-exporter: tenet
  event-exporter-app: tenet
  exception-recommender: shield
  external-dns-app: cabbage
  external-secrets: honeybadger
  falco: shield
  fluent-logshipping-app: atlas
  flux-app: honeybadger
  flux-operator: honeybadger
  fulfillment: planeteers
  gateway-api-bundle: cabbage
  gateway-api-config: cabbage
  gateway-api-crds: cabbage
  gel: shield
  goldilocks: tenet
  gpu-operator: tenet
  grafana: atlas
  handbook: up
  fe-docs: honeybadger
  happa: honeybadger
  headlamp: planeteers
  hello-world: honeybadger
  image-distribution-operator: rocket
  ingress-nginx: cabbage
  ingress-sla: cabbage
  inspektor-gadget: planeteers
  irsa-operator: phoenix
  irsa-servicemonitors: phoenix
  jiralert: shield
  k8s-audit-metrics: tenet
  k8s-dns-node-cache-app: cabbage
  kamaji: rocket
  kamaji-etcd: rocket
  karpenter-bundle: phoenix
  karpenter: phoenix
  karpenter-crossplane-resources: phoenix
  keda: atlas
  konfigure-operator: honeybadger
  kong-app: cabbage
  kube-downscaler: planeteers
  kube-prometheus-stack: atlas
  kube-state-metrics: tenet
  kube-vip: rocket
  kube-vip-cloud-provider: rocket
  kubeedge-cloudcore: rocket
  kubescape: shield
  kyverno: shield
  kyverno-crds: shield
  kyverno-policies: shield
  kyverno-policies-connectivity: cabbage
  kyverno-policies-dx: honeybadger
  kyverno-policies-observability: atlas
  kyverno-policies-ux: honeybadger
  kyverno-policy-operator: shield
  loadtest-app: cabbage
  local-path-provisioner: rocket
  loki: atlas
  mcp-kubernetes: planeteers
  mcp-prometheus: planeteers
  metrics-server-app: atlas
  mimir: atlas
  muster: planeteers
  n8n: planeteers
  net-exporter: cabbage
  network-policies: cabbage
  node-exporter-app: tenet
  node-problem-detector: phoenix
  nos: planeteers
  object-storage-operator: atlas
  observability-bundle: atlas
  observability-platform-api: atlas
  observability-policies: atlas
  oncall-shift-reporter: planeteers
  onepassword-scim-bridge: shield
  openssf-scorecard-exporter: shield
  operational-load-exporter: planeteers
  organization-operator: shield
  pg-cluster-recovery-test: atlas
  plugin-barman-cloud: atlas
  policy-api-crds: shield
  policy-meta-operator: shield
  priority-classes: tenet
  prometheus-blackbox-exporter: phoenix
  prometheus-operator-crd: atlas
  prometheus-rules: atlas
  proxmox-csi-plugin: rocket
  proxysocks: cabbage
  pyroscope: atlas
  rbac-bootstrap: shield
  rbac-operator: shield
  release-exporter: planeteers
  reports-server: shield
  resource-police: phoenix
  schema-server: honeybadger
  search-mcp: honeybadger
  security-bundle: shield
  shoot-controller: phoenix
  sloth: atlas
  squid-proxy: phoenix
  starboard-exporter: shield
  team-stamper: honeybadger
  tekton-dashboard-loki-proxy: tenet
  teleport-exporter: shield
  teleport-kube-agent: shield
  teleport-operator: shield
  teleport-tbot: shield
  tempo: atlas
  test-app: honeybadger
  trivy: shield
  trivy-operator: shield
  valkey: planeteers
  velero: tenet
  vertical-pod-autoscaler-app: tenet
  vertical-pod-autoscaler-crd: tenet
  vsphere-csi-driver: rocket
  zot: honeybadger
