apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./oci-repository.yaml
  - ./valkey-oci-repository.yaml
  - ./helm-release.yaml
  - ./valkey-helm-release.yaml
  - ./konfiguration.yaml

